Creation of the entites Recurso and Tarea, their DAOs, DTOs and mappers
globant-bootcamps/bootcamp-java-proyecto-final pull request #10
Opened 2021-06-22 15:57 UTC by olvann

2021-06-22 16:38 UTC, FreddySolis requested changes
Los nombres de las entidades deberían ser en inglés para estandarizar el código de acuerdo al diagrama. Agradecería mucho que nos apegáramos a eso.

2021-06-22 19:06 UTC, olvann commented
> Los nombres de las entidades deberían ser en inglés para estandarizar el código de acuerdo al diagrama. Agradecería mucho que nos apegáramos a eso.

Hicimos los cambios a inglés @FreddySolis

2021-06-22 20:15 UTC, FreddySolis approved these changes

2021-06-22 22:58 UTC, eduardotorrezh approved these changes
Excelente, muchas gracias por hacer la correción.

2021-06-23 01:55 UTC, globant-bootcamps requested changes

2021-06-23 01:55 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/entity/Recurso.java
> +@Table(name = "recurso")
put the name "recurso" in english

2021-06-23 01:55 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/entity/Recurso.java
> +    private String enlace;
put the name "enlace" in english

2021-06-23 01:55 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/entity/Tarea.java
> +public class Tarea {
put the name "tarea" in english

2021-06-23 01:55 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/entity/Tarea.java
> +    private String nombre_tarea;
put the name "nombre_tarea" in english

2021-06-23 01:55 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/entity/Tarea.java
> +    private String enlace_tarea;
put the name "enlace_tarea" in english

2021-06-23 02:09 UTC, globant-bootcamps approved these changes

2021-06-23 02:11 UTC, merged