Add-Resource
globant-bootcamps/bootcamp-java-proyecto-final pull request #25
Opened 2021-06-23 18:22 UTC by Zureyma-Manrique

2021-06-23 18:29 UTC, fminajasc1000 requested changes
Zureyma dijo el jefe supremo que cambiaramos en los DTOS las clases por long, en caso de que existan relaciones.

2021-06-23 19:34 UTC, olvann reviewed
Gracias! me parece bien salvo por lo que comentaba Javier

2021-06-23 19:39 UTC, EriVelk approved these changes

2021-06-23 23:08 UTC, fminajasc1000 approved these changes

2021-06-24 02:36 UTC, olvann commented
Hay conflictos por los cambios que hicimos en DTO, me imagino que en el próximo push deberían desaparecer 👍

2021-06-24 02:37 UTC, olvann approved these changes
vamos bien equipo :)

2021-06-24 14:00 UTC, fminajasc1000 approved these changes
muy bien

2021-06-24 14:37 UTC, merged