Java daba dooo to master!
globant-bootcamps/bootcamp-java-proyecto-final pull request #58
Opened 2021-06-25 02:53 UTC by eduardotorrezh

This is the branch where the team 3 worked.

2021-06-25 13:52 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/controller/TrainingController.java
> +    TrainingService trainingService;
El training service no está en el proyecto. Adicionalmente estás haciendo uso de un service y no de la implementation correspondiente.

2021-06-25 13:54 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/entity/Student.java
> +import javax.persistence.*;
No es necesario que carguen todas las librerías, de hecho eso podría ocasionar problemas.

2021-06-25 13:54 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/entity/Training.java
> +import javax.persistence.*;
No es necesario que carguen todas las librerías, de hecho eso podría ocasionar problemas.

2021-06-25 13:58 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/utils/Validation.java
> +        if(email == null || email == ""){
Creo que esto se puede reemplazar por las sugerencias que dio Ad el día de ayer.

2021-06-25 13:59 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/GlobantApplicationTests.java
> +/**
¿Cuál es el objetivo de comentar todo el archivo?

2021-06-25 14:01 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +        //when(trainingDAO.getById(ONE_LONG)).thenReturn(training);
¿Cuál es el objetivo de dejar las líneas comentadas? Si no las necesitan, mejor elimínenlas.

2021-06-25 14:02 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +import com.bootcamp.globant.exception.InvalidDataException;
En el proyecto nuevamente  no se encuentra el paquete ni la clase.

2021-06-25 14:04 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +        //when(trainingDAO.getById(ONE_LONG)).thenReturn(training);
¿Cuál es el objetivo de dejar las líneas comentadas? Si no las necesitan, mejor elimínenlas.

2021-06-25 14:04 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +import com.bootcamp.globant.exception.InvalidDataException;
En el proyecto nuevamente no se encuentra el paquete ni la clase.

2021-06-25 14:05 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/entity/Training.java
> +import javax.persistence.*;
No es necesario que carguen todas las librerías, de hecho eso podría ocasionar problemas.

2021-06-25 14:05 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/entity/Student.java
> +import javax.persistence.*;
No es necesario que carguen todas las librerías, de hecho eso podría ocasionar problemas.

2021-06-25 14:05 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/controller/TrainingController.java
> +    TrainingService trainingService;
El training service no está en el proyecto. Adicionalmente estás haciendo uso de un service y no de la implementation correspondiente.

2021-06-25 14:07 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/TrainingControllerTest.java
> +    TrainingController trainingController;
Clase no encontrada en el proyecto

2021-06-25 14:07 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/controller/TrainingControllerTest.java
> +    TrainingService trainingService;
Clase no encontrada en el proyecto

2021-06-25 14:08 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/service/StudentServiceTest.java
> +//import org.mockito.InjectMocks;
Si no usan estos imports es mejor eliminarlos, hay que mantener el código limpio.

2021-06-25 14:08 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/service/StudentServiceTest.java
> +import com.bootcamp.globant.exception.InvalidDataException;
De igual manera, no se encuentra el paquete.

2021-06-25 14:09 UTC, FreddySolis commented on src/test/java/com/bootcamp/globant/service/TrainerServiceTest.java
> +    TrainerMapper trainerMapper;
No se encuentra la clase en el proyecto

2021-06-25 15:13 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/utils/Validation.java
> +        if(email == null || email == ""){
StringUtils.isEmpty

2021-06-25 15:24 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/controller/TrainerControllerTest.java
> +    TrainerController trainerController;
Done.

2021-06-25 15:24 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +        //when(trainingDAO.getById(ONE_LONG)).thenReturn(training);
Done.

2021-06-25 15:27 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/controller/StudentControllerTest.java
> +import com.bootcamp.globant.exception.InvalidDataException;
Done.

2021-06-25 15:37 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/service/TrainerServiceTest.java
> +    TrainerMapper trainerMapper;
Done.

2021-06-25 15:38 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/service/StudentServiceTest.java
> +import com.bootcamp.globant.exception.InvalidDataException;
Done.

2021-06-25 15:38 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/service/StudentServiceTest.java
> +//import org.mockito.InjectMocks;
Done.

2021-06-25 15:38 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/GlobantApplicationTests.java
> +/**
Done.

2021-06-25 15:38 UTC, globant-bootcamps requested changes

2021-06-25 15:38 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/StudentServiceImpl.java
> +        return DELETED_SUCCESSFULLY;
This method should not return anything, the message should by send in directly in the controller

2021-06-25 15:38 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
>  public class TrainerServiceImpl implements TrainerService {
Where is the TrainerService interface?

2021-06-25 15:38 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
Where is the TrainerMapper component?

2021-06-25 15:38 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
> +        return DELETED_SUCCESSFULLY;
This method should not return anything, the message should by send in directly in the controller

2021-06-25 15:38 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
>          return trainerMapper.TrainerToTrainerDTO(trainerDAO.save(trainerMapper.TrainerDTOToTrainer(trainerDTO)));
is TrainerToTrainerDTO s method? if it is, them need to be start with lowercase t, same for the TrainerDTOToTrainer

2021-06-25 15:42 UTC, globant-bootcamps commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
>          return trainerMapper.TrainerToTrainerDTO(trainerDAO.save(trainerMapper.TrainerDTOToTrainer(trainerDTO)));
Check also the method names inside de mappers.

2021-06-25 15:52 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
>          return trainerMapper.TrainerToTrainerDTO(trainerDAO.save(trainerMapper.TrainerDTOToTrainer(trainerDTO)));
Done.

2021-06-25 15:54 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
it lost in the merge, it was already added

2021-06-25 15:58 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/entity/Training.java
> +import javax.persistence.*;
Excelente observación, se se agregaron los imports de manera individual.

2021-06-25 15:58 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/entity/Student.java
> +import javax.persistence.*;
Excelente observación, se se agregaron los imports de manera individual.

2021-06-25 15:58 UTC, eduardotorrezh commented on src/test/java/com/bootcamp/globant/controller/TrainingControllerTest.java
> +    TrainingService trainingService;
Done.

2021-06-27 17:17 UTC, FreddySolis requested changes

2021-06-27 17:17 UTC, FreddySolis commented on src/main/java/com/bootcamp/globant/controller/StudentController.java
> +import static com.bootcamp.globant.utils.Constants.*;
¿Es necesario usar todas las constantes? Si no, hay que importar solo las que usamos

2021-06-27 19:58 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/controller/StudentController.java
> +import static com.bootcamp.globant.utils.Constants.*;
Done.

2021-06-27 20:18 UTC, eduardotorrezh commented on src/main/resources/application.yml
> +    password:
¿Es necesaria? H2 de momento es para pruebas.

2021-06-27 20:21 UTC, olvann commented on src/main/resources/application.yml
> +    password:
no

2021-06-27 20:24 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/StudentServiceImpl.java
> +        studentDAO.save(student);;
No.

2021-06-27 20:24 UTC, eduardotorrezh commented on src/main/resources/application.yml
> +    data-base-platform: org.hibernate.dialect.H2Dialect
Done.

2021-06-27 21:04 UTC, FreddySolis approved these changes

2021-06-27 21:32 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
>  public class TrainerServiceImpl implements TrainerService {
Done.

2021-06-27 21:56 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/TrainerServiceImpl.java
> +        return DELETED_SUCCESSFULLY;
Done

2021-06-27 21:57 UTC, eduardotorrezh commented on src/main/java/com/bootcamp/globant/service/impl/StudentServiceImpl.java
> +        return DELETED_SUCCESSFULLY;
Done.

2021-06-28 01:50 UTC, olvann commented on build.gradle
> +    implementation group: 'org.hibernate', name: 'hibernate-validator', version: '7.0.1.Final'
¿Dónde usan esta dependencia? Me interesa saber para ver si nos ayuda también

2021-06-29 00:42 UTC, merged